### PR TITLE
Bump dependencies. Update to less@3.9.0

### PR DESCRIPTION
**Pull request by eight04**
Fix security issues.

### CODE REVIEW

**Comment by eight04** [comment]
Since we have a test, do we want to setup travis for this repo?

**Comment by Mottie** [comment]
If you want to go through the trouble, then go for it.

**Comment by eight04** [comment]
I think I have no permission to access the organization settings:
https://help.github.com/en/articles/reviewing-your-organizations-installed-integrations

**Comment by Mottie** [comment]
I don't either... @narcolepticinsomniac.

**Comment by Mottie** [comment]
Ok, Narco added a webhook. We'll check if it works once we merge.

**Pull request merged**
