### PR TITLE
Change: build less from source

### LINKED ISSUE #5: Update LESS
%subj%

### PR DESCRIPTION
**Pull request by eight04**
Fixes #5.

Current the submodule points to the latest master.

@tophf do you want to open a new issue for sourcemap? Actually, I'm not sure whether we have excluded source map calculation from less.

### CODE REVIEW

**Comment by tophf** [comment]
I've tried using sourcemaps in usercss-compiler.js:

```js
      const res = await less.render(varDefs + source, {
        math: 'parens-division',
        sourceMap: {sourceMapFileInline: true},
      });
```

but I get "e.getSourceMapGenerator is not a function" both in current less and this one.

Other than that, the PR is probably fine because it works without sourcemaps.

**Comment by tophf** [comment]
What about bumping the `version`?

**Comment by eight04** [comment]
Tagged as 0.2.0

**Comment by tophf** [comment]
NPM doesn't download the new version for me even if I clear its cache manually.
Looking at our package-lock.json afterwards I see `0.2.0` but the url still points to the SHA of 0.1.0...
Publishing the bundle on npm would probably help.

**Comment by eight04** [comment]
We didn't publish this repo to npm. The code is fetched from Github directly:
https://github.com/openstyles/stylus/blob/f740686cb50d67b809bcfd581b37244a9fe1df0c/package.json#L16
In Stylus, we have to run:
```
npm install openstyles/less-bundle#v0.2.0
```
To switch to v0.2.0.

**Comment by tophf** [comment]
Isn't this what NPM does when I run `npm install`? I've already edited package.json to `openstyles/less-bundle#v0.2.0`

**Comment by eight04** [comment]
> Isn't this what NPM does when I run `npm install`? I've already edited package.json to `openstyles/less-bundle#v0.2.0`

Seems like a bug in npm:
https://github.com/npm/cli/issues/2844

BTW I found that we accidentally used a prod dependency:
https://github.com/openstyles/less-bundle/blob/42c7eb52d24402cc75eebf95ca9a8ea2b9326f1d/package.json#L44-L46
Let me fix it and tag a new version.

**Pull request merged**
